version: 2

sources:
  - name: source
    tables:
      - name: frs_program_links
        columns:
          - name: pgm_sys_acrnm
          - name: pgm_sys_id
          - name: registry_id
          - name: primary_name
          - name: location_address
          - name: supplemental_location
          - name: city_name
          - name: county_name
          - name: fips_code
          - name: state_code
          - name: state_name
          - name: country_name
          - name: postal_code
      - name: wifia_loans_closed
        columns:
          - name: seq
          - name: borrower
          - name: project name
          - name: state
          - name: close date
          - name: loan amount
          - name: environmental compliance
      - name: wifia_projects_selected
        columns:
          - name: seq
          - name: fiscal year
          - name: borrower
          - name: project name
          - name: loan  amount
          - name: state
          - name: approval status
      - name: wifia_letters_submitted
        columns:
          - name: seq
          - name: fiscal year
          - name: prospective borrower
          - name: state
          - name: project description
      - name: npdes_informal_enforcement_actions
        columns:
          - name: npdes_id
          - name: registry_id
          - name: agency
          - name: activity_id
          - name: activity_type_code
          - name: activity_type_desc
          - name: enf_type_code
          - name: enf_type_desc
          - name: achieved_date
          - name: enf_identifier
          - name: official_flg
      - name: frs_facilities
        columns:
          - name: fac_name
          - name: fac_street
          - name: fac_city
          - name: fac_state
          - name: fac_zip
          - name: registry_id
          - name: fac_county
          - name: fac_epa_region
          - name: latitude_measure
          - name: longitude_measure
      - name: frs_naics_codes
        columns:
          - name: pgm_sys_id
          - name: pgm_sys_acnrm
          - name: naics_code
          - name: registry_id
      - name: npdes_naics
        columns:
          - name: npdes_id
          - name: naics_code
          - name: naics_desc
          - name: primary_indicator_flag
      - name: npdes_formal_enforcement_actions
        columns:
          - name: npdes_id
          - name: enf_identifier
          - name: activity_id
          - name: activity_type_code
          - name: enf_type_code
          - name: enf_type_desc
          - name: agency
          - name: settlement_entered_date
          - name: fed_penalty_assessed_amt
          - name: state_local_penalty_amt
      - name: frs_sic_codes
        columns:
          - name: pgm_sys_id
          - name: pgm_sys_acnrm
          - name: sic_code
          - name: registry_id
      - name: npdes_sics
        columns:
          - name: npdes_id
          - name: sic_code
          - name: sic_desc
          - name: primary_indicator_flag
      - name: epa_informal_enforcement_actions
        columns:
          - name: pgm_sys_id
          - name: registry_id
          - name: agency
          - name: activity_type_code
          - name: enf_type_code
          - name: enf_type_desc
          - name: achieved_date
          - name: enf_identifier
          - name: statute