create role lindsey password 'r3data1' login nosuperuser nocreatedb nocreaterole noreplication;
create role kyle password 'r3data2' login nosuperuser nocreatedb nocreaterole noreplication;
create role tblusr password 'r3data.2022!' login nosuperuser nocreatedb nocreaterole noreplication;

GRANT SELECT ON TABLE main.fact_epa_informal_actions TO kyle;
GRANT SELECT ON TABLE main.fact_programs TO kyle;
GRANT SELECT ON TABLE staging.stg_epa_informal_enforcement_actions TO kyle;
GRANT SELECT ON TABLE staging.stg_frs_facilities TO kyle;
GRANT SELECT ON TABLE staging.stg_frs_naics_codes TO kyle;
GRANT SELECT ON TABLE staging.stg_frs_programs TO kyle;
GRANT SELECT ON TABLE staging.stg_frs_sics_codes TO kyle;
GRANT SELECT ON TABLE staging.stg_naics_codes TO kyle;
GRANT SELECT ON TABLE staging.stg_npdes_formal_enforcement_actions TO kyle;
GRANT SELECT ON TABLE staging.stg_npdes_informal_enforcement_actions TO kyle;
GRANT SELECT ON TABLE staging.stg_npdes_naics_codes TO kyle;
GRANT SELECT ON TABLE staging.stg_npdes_sic_codes TO kyle;
GRANT SELECT ON TABLE "source".epa_informal_enforcement_actions TO kyle;
GRANT SELECT ON TABLE "source".frs_facilities TO kyle;
GRANT SELECT ON TABLE "source".frs_naics_codes TO kyle;
GRANT SELECT ON TABLE "source".frs_program_links TO kyle;
GRANT SELECT ON TABLE "source".frs_sic_codes TO kyle;
GRANT SELECT ON TABLE "source".npdes_formal_enforcement_actions TO kyle;
GRANT SELECT ON TABLE "source".npdes_informal_enforcement_actions TO kyle;
GRANT SELECT ON TABLE "source".npdes_naics TO kyle;
GRANT SELECT ON TABLE "source".npdes_sics TO kyle;
GRANT SELECT ON TABLE seed_data.src_states TO kyle;

GRANT SELECT ON TABLE main.fact_epa_informal_actions TO lindsey;
GRANT SELECT ON TABLE main.fact_programs TO lindsey;
GRANT SELECT ON TABLE staging.stg_epa_informal_enforcement_actions TO lindsey;
GRANT SELECT ON TABLE staging.stg_frs_facilities TO lindsey;
GRANT SELECT ON TABLE staging.stg_frs_naics_codes TO lindsey;
GRANT SELECT ON TABLE staging.stg_frs_programs TO lindsey;
GRANT SELECT ON TABLE staging.stg_frs_sics_codes TO lindsey;
GRANT SELECT ON TABLE staging.stg_naics_codes TO lindsey;
GRANT SELECT ON TABLE staging.stg_npdes_formal_enforcement_actions TO lindsey;
GRANT SELECT ON TABLE staging.stg_npdes_informal_enforcement_actions TO lindsey;
GRANT SELECT ON TABLE staging.stg_npdes_naics_codes TO lindsey;
GRANT SELECT ON TABLE staging.stg_npdes_sic_codes TO lindsey;
GRANT SELECT ON TABLE "source".epa_informal_enforcement_actions TO lindsey;
GRANT SELECT ON TABLE "source".frs_facilities TO lindsey;
GRANT SELECT ON TABLE "source".frs_naics_codes TO lindsey;
GRANT SELECT ON TABLE "source".frs_program_links TO lindsey;
GRANT SELECT ON TABLE "source".frs_sic_codes TO lindsey;
GRANT SELECT ON TABLE "source".npdes_formal_enforcement_actions TO lindsey;
GRANT SELECT ON TABLE "source".npdes_informal_enforcement_actions TO lindsey;
GRANT SELECT ON TABLE "source".npdes_naics TO lindsey;
GRANT SELECT ON TABLE "source".npdes_sics TO lindsey;
GRANT SELECT ON TABLE seed_data.src_states TO lindsey;

GRANT SELECT ON TABLE main.fact_epa_informal_actions TO tblusr;
GRANT SELECT ON TABLE main.fact_programs TO tblusr;
GRANT SELECT ON TABLE seed_data.src_states TO tblusr;
